/* Sunlit Atlas service worker · generated by tools/build_share.js · build 1210bdd874 */
var CACHE = "sunlit-atlas-1210bdd874";
var VAULT = "/vault-082b3cc503/";
var PRECACHE = ["./","index.html","manifest.json","icon-192.png","icon-512.png","icon-512-maskable.png","apple-touch-icon.png","vault-082b3cc503/thai-lion-sl605-eticket-2026-09-26.pdf","vault-082b3cc503/siam-mandarina-bangkok-expedia-confirmation.pdf","vault-082b3cc503/aa-mia-jax-schedule-change-2026-09-22.jpeg","vault-082b3cc503/qatar-reissued-eticket-2026-06-29.pdf","vault-082b3cc503/qatar-schedule-change-thread-2026-06-29.pdf","vault-082b3cc503/qatar-original-eticket-2026-04-04.pdf","vault-082b3cc503/qatar-booking-confirmation-2026-04-04.pdf","vault-082b3cc503/aa-mia-jax-chase-confirmation.pdf","vault-082b3cc503/aa-jax-lim-chase-confirmation.pdf","vault-082b3cc503/latam-lim-mia-chase-confirmation.pdf","vault-082b3cc503/fairfield-miami-airport-confirmation.pdf","vault-082b3cc503/miami-airport-marriott-confirmation.pdf","vault-082b3cc503/jack-itinerary-2026-revised.xlsx","vault-082b3cc503/jack-itinerary-2026-original.xlsx","vault-082b3cc503/peru-and-chile-parents-sheet.xlsx"];

self.addEventListener("install", function (e) {
  e.waitUntil(caches.open(CACHE).then(function (c) {
    return Promise.all(PRECACHE.map(function (u) {
      return c.add(new Request(u, { cache: "reload" })).catch(function () { /* one missing file never blocks the install */ });
    }));
  }).then(function () { return self.skipWaiting(); }));
});

self.addEventListener("activate", function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) { return k.indexOf("sunlit-atlas-") === 0 && k !== CACHE; }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

/* shell: network first (fresh itinerary when online), the saved copy when not, with a 6 s patience limit */
function networkFirst(req, key) {
  return new Promise(function (resolve) {
    var done = false;
    var timer = setTimeout(function () {
      caches.match(key).then(function (hit) { if (hit && !done) { done = true; resolve(hit); } });
    }, 6000);
    fetch(req).then(function (r) {
      clearTimeout(timer);
      if (r && r.ok) { var copy = r.clone(); caches.open(CACHE).then(function (c) { c.put(key, copy); }); }
      if (!done) { done = true; resolve(r); }
    }).catch(function () {
      clearTimeout(timer);
      caches.match(key).then(function (hit) { if (!done) { done = true; resolve(hit || Response.error()); } });
    });
  });
}
/* documents, icons, manifest: the saved copy first, the network as fallback (and remembered) */
function cacheFirst(req) {
  return caches.match(req).then(function (hit) {
    if (hit) return hit;
    return fetch(req).then(function (r) {
      if (r && r.ok) { var copy = r.clone(); caches.open(CACHE).then(function (c) { c.put(req, copy); }); }
      return r;
    });
  });
}

self.addEventListener("fetch", function (e) {
  var req = e.request;
  if (req.method !== "GET") return;
  var url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (url.pathname.indexOf(VAULT) >= 0) { e.respondWith(cacheFirst(req)); return; }
  if (req.mode === "navigate" || /\/(index\.html)?$/.test(url.pathname)) { e.respondWith(networkFirst(req, "index.html")); return; }
  e.respondWith(cacheFirst(req));
});
