/* Sunlit Atlas service worker · generated by tools/build_share.js · build 34bc7fd982 */
var CACHE = "sunlit-atlas-34bc7fd982";
var VAULT = "/vault-082b3cc503/";
var PRECACHE = ["./","index.html","manifest.json","icon-192.png","icon-512.png","icon-512-maskable.png","apple-touch-icon.png","vault-082b3cc503/thai-lion-sl605-eticket-2026-09-26.pdf","vault-082b3cc503/siam-mandarina-bangkok-expedia-confirmation.pdf","vault-082b3cc503/aa-mia-jax-schedule-change-2026-09-22.jpeg","vault-082b3cc503/qatar-reissued-eticket-2026-06-29.pdf","vault-082b3cc503/qatar-schedule-change-thread-2026-06-29.pdf","vault-082b3cc503/qatar-original-eticket-2026-04-04.pdf","vault-082b3cc503/qatar-booking-confirmation-2026-04-04.pdf","vault-082b3cc503/aa-mia-jax-chase-confirmation.pdf","vault-082b3cc503/aa-jax-lim-chase-confirmation.pdf","vault-082b3cc503/latam-lim-mia-chase-confirmation.pdf","vault-082b3cc503/fairfield-miami-airport-confirmation.pdf","vault-082b3cc503/miami-airport-marriott-confirmation.pdf","vault-082b3cc503/jack-itinerary-2026-revised.xlsx","vault-082b3cc503/jack-itinerary-2026-original.xlsx","vault-082b3cc503/peru-and-chile-parents-sheet.xlsx"];

/* install: the shell and manifest MUST arrive (a broken install never replaces a good cache);
   documents are copied across from the previous cache when already held, so a new build does not re-download them */
self.addEventListener("install", function (e) {
  e.waitUntil(caches.open(CACHE).then(function (c) {
    var essential = ["index.html", "manifest.json"];
    return Promise.all(essential.map(function (u) { return c.add(new Request(u, { cache: "reload" })); }))
      .then(function () { return caches.keys(); })
      .then(function (keys) {
        var old = keys.filter(function (k) { return k.indexOf("sunlit-atlas-") === 0 && k !== CACHE; });
        return Promise.all(PRECACHE.filter(function (u) { return essential.indexOf(u) < 0; }).map(function (u) {
          var isDoc = u.indexOf(VAULT.slice(1)) === 0;
          var reuse = isDoc ? Promise.all(old.map(function (k) { return caches.open(k).then(function (oc) { return oc.match(u); }); }))
            .then(function (hits) { return hits.filter(Boolean)[0] || null; }) : Promise.resolve(null);
          return reuse.then(function (hit) {
            if (hit) return c.put(u, hit);
            return c.add(new Request(u, { cache: "reload" })).catch(function () { /* one missing document never blocks the install */ });
          });
        }));
      });
  }).then(function () { return self.skipWaiting(); }));
});

self.addEventListener("activate", function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) { return k.indexOf("sunlit-atlas-") === 0 && k !== CACHE; }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

/* shell: network first (fresh itinerary when online), the saved copy when not, with a 6 s patience limit */
function networkFirst(req, key) {
  return new Promise(function (resolve) {
    var done = false;
    var timer = setTimeout(function () {
      caches.match(key).then(function (hit) { if (hit && !done) { done = true; resolve(hit); } });
    }, 6000);
    fetch(req).then(function (r) {
      clearTimeout(timer);
      if (r && r.ok) { var copy = r.clone(); caches.open(CACHE).then(function (c) { c.put(key, copy); }); if (!done) { done = true; resolve(r); } return; }
      /* a host error page never replaces a good cached shell */
      caches.match(key).then(function (hit) { if (!done) { done = true; resolve(hit || r); } });
    }).catch(function () {
      clearTimeout(timer);
      caches.match(key).then(function (hit) { if (!done) { done = true; resolve(hit || Response.error()); } });
    });
  });
}
/* documents, icons, manifest: the saved copy first, the network as fallback (and remembered) */
function cacheFirst(req) {
  return caches.match(req).then(function (hit) {
    if (hit) return hit;
    return fetch(req).then(function (r) {
      if (r && r.ok) { var copy = r.clone(); caches.open(CACHE).then(function (c) { c.put(req, copy); }); }
      return r;
    });
  });
}

/* a tapped reminder brings the app to the front on the Now screen */
self.addEventListener("notificationclick", function (e) {
  e.notification.close();
  var scope = self.registration.scope;
  e.waitUntil(self.clients.matchAll({ type: "window", includeUncontrolled: true }).then(function (cs) {
    var app = cs.filter(function (c) { var p = new URL(c.url).pathname; return p === new URL(scope).pathname || /\/index\.html$/.test(p); })[0];
    if (app) { return app.focus().then(function (w) { try { if (w && w.navigate && !/#\/now/.test(w.url)) return w.navigate(scope + "index.html#/now"); } catch (err) {} return w; }); }
    return self.clients.openWindow(scope + "index.html#/now");
  }));
});

self.addEventListener("fetch", function (e) {
  var req = e.request;
  if (req.method !== "GET") return;
  var url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (url.pathname.indexOf(VAULT) >= 0) { e.respondWith(cacheFirst(req)); return; }
  /* only the shell itself is the shell: a navigation to robots.txt or an icon must never overwrite the cached app */
  var scopePath = new URL(self.registration.scope).pathname;
  var isShell = url.pathname === scopePath || url.pathname === scopePath + "index.html";
  if (isShell) { e.respondWith(networkFirst(req, "index.html")); return; }
  e.respondWith(cacheFirst(req));
});
